name: BlackHole CI
on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm run install
      - run: npm run build